name: Build SAMU Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 34
        build-tools: 34.0.0
        
    - name: Install Dependencies
      run: |
        npm ci
        npm install -g @ionic/cli @capacitor/cli
      
    - name: Build Web Application
      run: npm run build
      
    - name: Capacitor Sync
      run: npx cap sync android
      
    - name: Grant Execute Permission
      run: chmod +x android/gradlew
      
    - name: Build Debug APK
      working-directory: ./android
      run: ./gradlew assembleDebug --no-daemon --stacktrace
      
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: samu-android-apk-${{ github.run_number }}
        path: android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30
        
    - name: Create GitHub Release
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        name: SAMU App v${{ github.run_number }}
        body: |
          # SAMU Meme Contest Mobile App
          
          ## 🚀 Features
          - Phantom Wallet Integration
          - SAMU Token Balance Display
          - Meme Upload & Voting System
          - Goods Shop with Token Payments
          - Mobile-Optimized UI
          
          ## 📱 Installation
          1. Download `app-debug.apk` from Assets below
          2. Enable "Unknown sources" in Android Settings
          3. Install the APK file
          
          ## 🔗 Links
          - Web App: https://meme-chain-rally-wlckddbs12345.replit.app
          - Repository: ${{ github.server_url }}/${{ github.repository }}
          
        files: |
          android/app/build/outputs/apk/debug/app-debug.apk
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build Summary
      run: |
        echo "✅ APK Build Completed Successfully"
        echo "📱 File: android/app/build/outputs/apk/debug/app-debug.apk"
        echo "📦 Size: $(du -h android/app/build/outputs/apk/debug/app-debug.apk | cut -f1)"
        echo "🔗 Download from Actions Artifacts or GitHub Releases"